# Base clothing that can be equipped without removing a coat or similar outer clothing
- id: ClothingUniformShirtlessBase
  components:
  - type: Tag #DeltaV, needed for species with nonhuman legs/can only wear skirts
    tags:
    - ClothMade
    - WhitelistChameleon
    - Skirt
    - ShirtlessClothing # to allow equipping/unequipping under coats and the like

- id: ClothingUniformThongBase
  parent: [ClothingUniformShirtlessBase, ClothingUniformBase]
