- type: gameMap
  id: Meta
  mapName: 'Meta Station'
  mapPath: /Maps/Floof/meta.yml
  minPlayers: 40 #
  maxPlayers: 85 #
  stations:
    Meta:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: '{0} Meta Station {1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'TG'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_meta.yml
        - type: StationJobs
          availableJobs:
            #service
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            Bartender: [ 2, 2 ]
            Botanist: [ 2, 3 ]
            Chef: [ 2, 2 ]
            Janitor: [ 1, 2 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 2 ]
            Reporter: [ 1, 1 ]
            #engineering
            ChiefEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 5, 7 ]
            TechnicalAssistant: [ 3, 6 ]
            SeniorEngineer: [ 1, 1 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            Chemist: [ 3, 3 ]
            MedicalDoctor: [ 5, 5 ]
            MedicalIntern: [ 3, 6 ]
            Paramedic: [ 1, 3 ]
            SeniorPhysician: [ 1, 1 ]
            #science
            ResearchDirector: [ 1, 1 ]
            Scientist: [ 5, 7 ]
            ResearchAssistant: [ 3, 6 ]
            Chaplain: [ 1, 1 ]
            Roboticist: [ 1, 2 ]
            ForensicMantis: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 5, 7 ]
            Detective: [ 1, 1 ]
            SecurityCadet: [ 3, 6 ]
            Brigmedic: [ 1, 1 ]
            Prisoner: [ 2, 3 ]
            PrisonGuard: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
            MailCarrier: [ 1, 2 ]
            InventorySpecialist: [ 1, 1 ] #FloofStation
            #civilian
            Passenger: [ -1, -1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            Anomaly: [ 4, 4 ] # Floofstation
            #silicon
            Borg: [ 2, 2 ]
            MedicalBorg: [ 2, 2 ]
            #justice added by FloofStation
            ChiefJustice: [ 1, 1 ] #FloofStation
            Clerk: [ 1, 1 ] #FloofStation
            Lawyer: [ 2, 2 ] #FloofStation
            Prosecutor: [ 1, 1 ] #FloofStation