- type: gameMap
  id: Train
  mapName: 'Train'
  mapPath: /Maps/Floof/train.yml
  minPlayers: 45
  maxPlayers: 80
  stations:
    Train:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Train "Sentipode" {0}-{1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'ED'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/DeltaV/NTES_Delta.yml #floofstation
        - type: StationJobs
          overflowJobs:
            - Passenger
          availableJobs:
            #service
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            Bartender: [ 1, 1 ]
            Botanist: [ 2, 2 ]
            Chef: [ 1, 1 ]
            Janitor: [ 1, 2 ]
            ServiceWorker: [ 2, 3 ]
            #engineering
            ChiefEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 2, 2 ]
            StationEngineer: [ 4, 4 ]
            TechnicalAssistant: [ 2, 2 ]
            SeniorEngineer: [ 1, 1 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 2, 2 ]
            MedicalIntern: [ 2, 2 ]
            Paramedic: [ 1, 1 ]
            Psychologist: [ 1, 1 ]
            SeniorPhysician: [ 1, 1 ]
            #science
            ResearchDirector: [ 1, 1 ]
            Scientist: [ 4, 4 ]
            ResearchAssistant: [ 2, 2 ]
            ForensicMantis: [ 1, 1 ]
            Roboticist: [ 1, 1 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 6, 6 ]
            SecurityCadet: [ 2, 2 ]
            Brigmedic: [ 1, 1 ]
            PrisonGuard: [ 1, 1 ]
            Prisoner: [ 2, 2 ]
            Detective: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            #supply
            Quartermaster: [ 1, 1 ]
            InventorySpecialist: [ 1, 1 ] #FloofStation
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
            MailCarrier: [ 1, 2 ]
            #civilian
            Passenger: [ -1, -1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            Borg: [ 2, 2 ]
            Reporter: [ 1, 1 ]
            #justice
            Lawyer: [ 1, 2 ]
            Anomaly: [ 4, 4 ] # Floofstation

