# General security
- type: loadout
  id: LoadoutClothingHandsSecurityWarmers
  category: JobsSecurity
  cost: 2
  exclusive: true
  items:
  - ClothingHandsSecurityWarmers
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - SecurityOfficer
    - SecurityCadet
    - Warden
    - Detective
    - HeadOfSecurity

- type: loadout
  id: LoadoutClothingUnderSocksSecurity
  category: JobsSecurity
  cost: 2
  exclusive: true
  items:
  - ClothingUnderSocksSecurity
  requirements:
  - !type:CharacterSpeciesRequirement
    inverted: true
    species:
    - Diona
    - Harpy
  - !type:CharacterJobRequirement
    jobs:
    - SecurityOfficer
    - SecurityCadet
    - Warden
    - Detective
    - HeadOfSecurity

- type: loadout
  id: LoadoutClothingUniformSecurityThong
  category: JobsSecurity
  cost: 2
  exclusive: true
  items:
  - ClothingUniformSecurityThong
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - SecurityOfficer
    - SecurityCadet
    - Warden
    - Detective
    - HeadOfSecurity

- type: loadout
  id: LoadoutSecurityNeckCollar
  category: JobsSecurity
  cost: 1
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - SecurityOfficer
    - Warden
    - HeadOfSecurity
  items:
  - ClothingNeckCollarSec

# Detective
- type: loadout
  id: LoadoutClothingHandsDetectiveWarmers
  category: JobsSecurity
  cost: 1
  exclusive: true
  items:
  - ClothingHandsDetectiveWarmers
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - Detective

- type: loadout
  id: LoadoutClothingUnderSocksDetective
  category: JobsSecurity
  cost: 1
  exclusive: true
  items:
  - ClothingUnderSocksDetective
  requirements:
  - !type:CharacterSpeciesRequirement
    inverted: true
    species:
    - Diona
    - Harpy
  - !type:CharacterJobRequirement
    jobs:
    - Detective

- type: loadout
  id: LoadoutClothingUniformDetectiveThong
  category: JobsSecurity
  cost: 1
  exclusive: true
  items:
  - ClothingUniformDetectiveThong
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - Detective
