- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: true
  joinNotifyCrew: false # Prevents players from getting spooked on CC spawn into round.
  whitelisted: true # Admin only role.
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom # Adjusted from HoS, CC answers to CC so.
  canBeAntag: false
  canBeAntagTarget: false # Prevention for worst case scenario of an antag rolling for CC.
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special: # Mindshield for lore purposes
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear # Adjusted for Floof based on typical CC outfitting.
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomFormal
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcomcap
    neck: ClothingNeckCloakCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    satchel: ClothingBackpackSatchelLeather
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
