- type: job
  id: InventorySpecialist
  name: job-name-invspec
  description: job-description-invspec
  playTimeTracker: JobInventorySpecialist
  setPreference: true
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics
      min: 144000 #floof to match the other seniors
    - !type:CharacterPlaytimeRequirement # Floof
      tracker: JobCourier
      min: 9000 # 2.5 Hours
  antagAdvantage: 2 # DeltaV - Reduced TC: External Access
  startingGear: InvSpecGear
  icon: "JobIconInventorySpecialist"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Orders
  extendedAccess:
  - Salvage
  - Mail

- type: startingGear
  id: InvSpecGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackCargoFilled
    shoes: ClothingShoesColorBlack
    id: InvSpecPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelCargoFilled
  duffelbag: ClothingBackpackDuffelCargoFilled
