- type: department
  id: CentralCommand
  description: department-CentComm-description
  color: "#009100"
  roles:
    - CentralCommandOfficial
  primary: false
  weight: 1000 # Heavy lies the crown on the king's head