- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  setPreference: true # DeltaV - Disable Senior Roles round start selection #floof - toggle to true to reenable
  requirements:
    - !type:CharacterDepartmentTimeRequirement # Floofstation
      department: Security # Floofstation
      min: 144000 # Floofstation 40 hrs# Floofstation
    - !type:CharacterPlaytimeRequirement # Floofstation
      tracker: JobSecurityOfficer # Floofstation
      min: 21600 # Floofstation - 6 hour
    - !type:CharacterPlaytimeRequirement # Floofstation
      tracker: JobWarden # Floofstation
      min: 21600 # Floofstation - 6 hour
    - !type:CharacterPlaytimeRequirement # Floofstation
      tracker: JobDetective # Floofstation
      min: 21600 # Floofstation - 6 hour
    - !type:CharacterPlaytimeRequirement # Floofstation
      tracker: JobPrisonGuard # Floofstation
      min: 9000 # Floofstation - 2.5 hour
    - !type:CharacterPlaytimeRequirement # Floofstation
      tracker: JobBrigmedic # Floofstation
      min: 9000 # Floofstation - 2.5 hour
    - !type:CharacterPlaytimeRequirement # Floofstation
      tracker: JobHeadOfSecurity # Floofstation
      min: 21600 # Floofstation - 6 hour
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorOfficer
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSecurity
    outerClothing: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier
    id: SeniorOfficerPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerClothingSkirt: ClothingUniformJumpskirtSeniorOfficer
  satchel: ClothingBackpackSatchelSecurity
  duffelbag: ClothingBackpackDuffelSecurity
