- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:CharacterDepartmentTimeRequirement # DeltaV - Command dept time requirement
      department: Security
      min: 57600 # Floofstation - 16 hour
    - !type:CharacterPlaytimeRequirement # Floof
      tracker: JobSecurityOfficer #Floof
      min: 18000 # Floofstation - 5 hours
    - !type:CharacterPlaytimeRequirement # Floof
      tracker: JobPrisonGuard #Floof
      min:  9000 # Floofstation - 2.5 hours
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetAltSecurity # Floof - Warden spawns with HoS's headset
    belt: ClothingBeltSecurityFilled
  innerClothingSkirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurity
  duffelbag: ClothingBackpackDuffelSecurity
