- type: Interaction
  id: BaseMouth
  abstract: true
  priority: -15
  requiresCanInteract: true # Do check CanAccess
  checkInteractionBlocker: false # Don't check CanInteract
  requiresHands: false
  requiresConsciousness: true
