- type: entity
  id: CrateServiceReplacementColoredLights
  name: Colored Lights Crate
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxColoredLighttube
        amount: 2
      - id: BoxLighttubeColorMixed # Floof Station
      - id: BoxLightbulbColorMixed # Floof Station

- type: entity
  id: CrateServiceReplacementMaintenanceLights
  name: Maintenance Lights Crate
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxMaintenanceLightbulb
        amount: 2
