- type: job
  id: SeniorEngineer
  name: Senior Engineer #floof
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  setPreference: false #floof - false makes it unable to be selected in round start selection #stub / tbr # Crow: Disabling senior roles until further review or better implimentation
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 14400 # Floofstation 4 hrs
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtSeniorEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
