- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Asterisk
  - Core
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Pebble
  - Saltern
  - Shoukou
  #- Submarine # Floof - Map Compleatly Broken, need rework.
  - Tortuga
  - TheHive
  #- Gax # Floof - Remvoe Gax due to mapping issues, power, access, etc.
  - Rad
  - Kettle
  - Fland
  - Train
