
- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Asterisk
  - Core
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Pebble
  - Saltern
  - Shoukou
  - Submarine
  - Tortuga
  - TheHive
  #- Gax # Floof - Remvoe Gax due to mapping issues, power, access, etc.
  - Rad
  - Kettle # Floof
  - Fland # Floof
  - Train # Floof
  - Amber # Floof
