- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Asterisk
  - Core
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Pebble
  - Saltern
  - Shoukou
  - Submarine
  - Tortuga
  - TheHive
  - Submarine # Floofstation - whatever this is
  - Gax
  - Rad
