# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTLeader
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    suitstorage: AirTankFilled
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledLeader
    neck: Whistle
    pocket1: WeaponPistolN1984
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxZiptie
    - MedkitCombatFilled
    - WeaponDisabler

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    suitstorage: AirTankFilled
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledLeader
    neck: Whistle
    pocket1: WeaponPistolN1984
    pocket2: CombatKnife
  storage:
    back:
    - BoxZiptie
    - MedkitCombatFilled
    - WeaponDisabler

- type: startingGear
  id: ERTMarinesGearLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    suitstorage: AirTankFilled
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledLeader
    neck: Whistle
    pocket1: WeaponPistolN1984
    pocket2: CombatKnife
  storage:
    back:
    - PortableRecharger
    - BoxZiptie
    - WeaponSubMachineGunDrozd
    - MedkitCombatFilled
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatFez
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    suitstorage: AirTankFilled
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledChaplain
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxBodyBag
    - BoxCandle
    - DrinkWaterMelonJuiceJug
    - AirTankFilled
    - FlippoEngravedLighter
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    suitstorage: AirTankFilled
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledChaplain
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxBodyBag
    - BoxCandle
    - DrinkWaterMelonJuiceJug
    - AirTankFilled
    - FlippoEngravedLighter
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX

- type: startingGear
  id: ERTMarinesGearPaladin
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    suitstorage: AirTankFilled
    id: ERTMarinePDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledChaplain
    pocket1: WeaponPistolMk58
    pocket2: EnergyShield
  storage:
    back:
    - BoxBodyBag
    - BoxCandle
    - ClaymoreHoly
    - MedkitCombatFilled
    - AirTankFilled
    - FlippoEngravedLighter

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTEngineer
    eyes: ClothingEyesHudDiagnostic
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    suitstorage: AirTankFilled
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledEngineer
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - RCD
    - SheetGlass
    - SheetGlass
    - SheetPlasteel
    - SheetSteel
    - SheetSteel
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - CableApcStack
    - CableMVStack
    - CableHVStack
    - MagazinePistol
    - MagazinePistol

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudDiagnostic
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    suitstorage: AirTankFilled
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledEngineer
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - RCD
    - SheetGlass
    - SheetGlass
    - SheetPlasteel
    - SheetSteel
    - SheetSteel
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - CableApcStack
    - CableMVStack
    - CableHVStack
    - MagazinePistol
    - MagazinePistol

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    suitstorage: AirTankFilled
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledSecurity
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxZiptie
    - MedkitCombatFilled
    - WeaponDisablerSMG
    - TelescopicShield

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitstorage: AirTankFilled
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledSecurity
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxZiptie
    - MedkitCombatFilled
    - WeaponDisablerSMG
    - TelescopicShield

- type: startingGear
  id: ERTMarinesGearBreacher
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitstorage: AirTankFilled
    id: ERTMarinePDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledSecurity
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxZiptie
    - WeaponShotgunEnforcer
    - MedkitCombatFilled
    - JawsOfLife
    - BoxLethalshot
    - BoxLethalshot
    - C4
    - C4
    - C4
    - C4
    - C4
    - C4

- type: startingGear
  id: ERTMarinesGearRifleman
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitstorage: AirTankFilled
    id: ERTMarinePDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledSecurity
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxZiptie
    - WeaponRifleLecter
    - MedkitCombatFilled
    - MagazineRifle
    - MagazineRifle
    - MagazineRifle
    - MagazineRifle

- type: startingGear
  id: ERTMarinesGearLaserRifleman
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitstorage: AirTankFilled
    id: ERTMarinePDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledSecurity
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  inhand:
  - WeaponLaserCannon
  storage:
    back:
    - BoxZiptie
    - WeaponSubMachineGunDrozd
    - MedkitCombatFilled
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun

- type: startingGear
  id: ERTMarinesGearGrenadier
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitstorage: AirTankFilled
    id: ERTMarinePDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledSecurity
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxZiptie
    - WeaponSubMachineGunDrozd
    - MedkitCombatFilled
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - SmokeGrenade
    - SmokeGrenade
    - GrenadeShrapnel
    - GrenadeShrapnel
    - GrenadeShrapnel
    - ExGrenade
    - ExGrenade
    - ExGrenade

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTMedic
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledMedical
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxBodyBag
    - MedkitCombatFilled
    - MedkitCombatFilled
    - JugPunct
    - JugTrico
    - JugPyra
    - LargeBeakerDex
    - LargeBeakerSaline
    - Hypospray
    - ClothingEyesGlassesChemical
    - OmnizineChemistryBottle
    - EphedrineChemistryBottle
    - EphedrineChemistryBottle
    - Syringe

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTMedical
    suitstorage: AirTankFilled
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledMedical
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxBodyBag
    - MedkitCombatFilled
    - MedkitCombatFilled
    - JugPunct
    - JugTrico
    - JugPyra
    - LargeBeakerDex
    - LargeBeakerSaline
    - Hypospray
    - ClothingEyesGlassesChemical
    - OmnizineChemistryBottle
    - EphedrineChemistryBottle
    - EphedrineChemistryBottle
    - Syringe

- type: startingGear
  id: ERTMarinesGearMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTMedical
    suitstorage: AirTankFilled
    id: ERTMarinePDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledMedical
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - WeaponSubMachineGunDrozd
    - MedkitCombatFilled
    - JugPunct
    - JugTrico
    - JugPyra
    - LargeBeakerDex
    - LargeBeakerSaline
    - Hypospray
    - ClothingEyesGlassesChemical
    - OmnizineChemistryBottle
    - EphedrineChemistryBottle
    - EphedrineChemistryBottle
    - Syringe

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesGaloshes
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTJanitor
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledJanitor
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxLightMixed
    - AdvMopItem
    - TrashBag
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    suitstorage: AirTankFilled
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingFilledJanitor
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxLightMixed
    - AdvMopItem
    - TrashBag
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
