- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Psychologist # DeltaV - Add Psychologist access
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackMedical # Floof - M3739 - #690 - Stamp is better off as a pocket2. Refer to lawyer starting gear.
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
    pocket2: RubberStampPsychologist # Floof - M3739 - #690
  innerClothingSkirt: ClothingUniformJumpsuitPsychologist
  satchel: ClothingBackpackSatchelPsychologistFilled #DeltaV - stamp included
  duffelbag: ClothingBackpackDuffelPsychologistFilled #DeltaV - stamp included
