- type: loadout
  id: LoadoutClothingHandsHeadSecurityWarmers
  category: JobsSecurityHeadOfSecurity
  cost: 1
  exclusive: true
  items:
  - ClothingHandsHeadSecurityWarmers
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - HeadOfSecurity

- type: loadout
  id: LoadoutClothingUnderSocksHeadSecurity
  category: JobsSecurityHeadOfSecurity
  cost: 1
  exclusive: true
  items:
  - ClothingUnderSocksHeadSecurity
  requirements:
  - !type:CharacterSpeciesRequirement
    inverted: true
    species:
    - Diona
    - Harpy
  - !type:CharacterJobRequirement
    jobs:
    - HeadOfSecurity

- type: loadout
  id: LoadoutClothingUniformHeadSecurityThong
  category: JobsSecurityHeadOfSecurity
  cost: 1
  exclusive: true
  items:
  - ClothingUniformHeadSecurityThong
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - HeadOfSecurity
