# Floof - base for vent critters. Adds the generic sound and popups.
- type: entity
  id: VentCrittersBase
  abstract: true
  components:
  - type: VentCrittersRule
    crawlTime: 5, 6.5 # The audio itself is 6 seconds long, so we don't want it to be much shorter or longer
    popup: station-event-generic-vents-popup
    sound:
      path: /Audio/Effects/sizzle.ogg
      params:
        volume: 0.8
        pitch: 0.667
