using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Floof.CharConsent.UI.Windows
{
    [GenerateTypedNameReferences]
    public sealed partial class ConsentText : FancyWindow
    {
        public Action<string>? OnConsentTextChanged;

        public ConsentText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();
            CConsentTextInput.Placeholder = new Rope.Leaf(loc.GetString("consent-text-placeholder"));
            CConsentTextInput.OnKeyBindDown += _ => ConsentTextChanged();
        }

        public void ConsentTextChanged()
        {
            OnConsentTextChanged?.Invoke(Rope.Collapse(CConsentTextInput.TextRope).Trim());
        }
    }
}
