- type: job
  id: Prosecutor
  name: job-name-prosecutor
  description: job-description-prosecutor
  playTimeTracker: JobProsecutor
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 36000 # 10 hrs
  startingGear: ProsecutorGear
  icon: "JobIconProsecutor"
  supervisors: job-supervisors-cj
  access:
  - Prosecutor
  - Justice
  - Security
  - Maintenance
# Floof - M3739 - Some of the equipment listed below has been commented out to keep consistency with other similiar roles.
- type: startingGear
  id: ProsecutorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitProsecutor
    # neck: ClothingNeckProsecutorbadge
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: ProsecutorPDA
    ears: ClothingHeadsetSecurity
    pocket1: HyperlinkBookSecuritySop # Floof - M3739 - Standardization across legal representatives. If the Attorney is going to have one, only makes sense that the Prosecutor does as well.
    pocket2: RubberStampLawyer # Floof - M3739 - DeltaV's Lawyer stamp addition is now a pocket item instead to ensure deployment across loadouts. ClothingBackpackLawyerFilled and it's variants don't really work when people can choose their bags.
    # TODO - Floof - M3739 - Make a stamp specific to the Prosecutor?
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtProsecutor
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled


