- type: job
  id: Freelancer
  name: Freelancer
  description: Freelancers and Merceneries of the free space
  playTimeTracker: JobFreelancer
  startingGear: FreelancerGear
  alwaysUseSpawner: false
  overrideConsoleVisibility: true
  canBeAntag: false
  canBeAntagTarget: false
  icon: "JobIconNoId"
  joinNotifyCrew: false
  whitelisted: true
  access:
  - Maintenance
  - Freelancer
  - External

- type: startingGear
  id: FreelancerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    shoes: ClothingShoesBootsMercFilled
    mask: ClothingMaskGasMerc
    neck: ClothingNeckOldMantle
    eyes: ClothingEyesGlassesMercenary
    gloves: ClothingHandsMercGlovesCombat
    outerClothing: ClothingOuterVestWebMercenary
    back: ClothingBackpackMerc
    id: FeelancerPDA
    ears: ClothingHeadsetAltFreelancer
    belt: ClothingBeltUtilityFilled
    pocket1: WeaponPistolPollock
    pocket2: HarmonicaInstrument