using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;


namespace Content.Client._Floof.Info;


[GenerateTypedNameReferences]
public sealed partial class NsfwDisclaimerWindow : FancyWindow
{
    [Dependency] private readonly IClientNetManager _netManager = default!;

    public NsfwDisclaimerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => Close();
        DeclineButton.OnPressed += _ =>
        {
            _netManager.ClientDisconnect("User rejected NSFW policy.");
        };
    }
}

