- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 144000 # Floofstation 40 hrs
    - !type:CharacterPlaytimeRequirement #floof
      tracker: JobScientist #floof
      min: 21600 #6 hours floof
    - !type:CharacterPlaytimeRequirement #floof
      tracker: JobRoboticist #floof
      min: 9000 #2.5 hours floof
    - !type:CharacterPlaytimeRequirement #floof
      tracker: JobForensicMantis #floof
      min: 9000 #2.5 hours floof
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  - Chapel # DeltaV - Chaplain is in Epistemics
  - Cryogenics
  special: # Nyanotrasen - Mystagogue can use the Bible
  - !type:AddComponentSpecial
    components:
    - type: BibleUser # Nyano - Lets them heal with bibles
    - type: Psionic # Nyano - They start with telepathic chat
      powerSlots: 3
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: InnatePsionicPowers
        powersToAdd:
          - DispelPower
          - MetapsionicPower
          - TelepathyPower

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    id: RnDPDA
    ears: ClothingHeadsetRD
    belt: BibleMystagogue # Nyanotrasen - Mystagogue book for their Ifrit
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
