- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements: #floof
  - !type:CharacterDepartmentTimeRequirement #floof
    department: Epistemics #floof
    min: 14400 # 4 hours - same as scientist
  - !type:CharacterPlaytimeRequirement #floof
      tracker: JobScientist #floof
      min: 9000 #2.5 hours floof
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: RoboticistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRoboticist
    back: ClothingBackpackRoboticsFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatRobo
    id: RoboticsPDA
    ears: ClothingHeadsetRobotics
  innerClothingSkirt: ClothingUniformJumpskirtRoboticist
  satchel: ClothingBackpackSatchelRoboticsFilled
  duffelbag: ClothingBackpackDuffelRoboticsFilled
