using System.Security.Cryptography.X509Certificates;
using Content.Shared._Floof.Examine;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Serilog;


namespace Content.Client._Floof.Examine;


[GenerateTypedNameReferences]
public sealed partial class CustomExaminePart : Control
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public string? Title { get; set; }
    public int MaxContentLength { get; set; }

    private CustomExamineData _lastData = new();
    private TimeSpan _lastUpdated = TimeSpan.MinValue;

    public CustomExaminePart()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Action<object?> onUpdate = _ => _lastUpdated = _timing.CurTime;
        Content.OnTextChanged += args =>
        {
            onUpdate(args);

            var text = Rope.Collapse(args.TextRope);
            var length = FormattedMessage.RemoveMarkupPermissive(text).Length;
            TextCounter.Text = $"{length}/{MaxContentLength} ";

            if (text.Length > SharedCustomExamineSystem.AbsolutelyMaxLength || length > MaxContentLength)
                TextCounter.Text += Loc.GetString("custom-examine-too-long");
        };
        NsfwCheckbox.OnToggled += onUpdate;
        DistanceSpin.ValueChanged += onUpdate;
        ExpirationSpin.ValueChanged += onUpdate;

        ExpirationHelpLabel.TooltipSupplier += _ =>
        {
            var tooltip = new Tooltip();
            var expiresIn = _lastData.ExpireTime - _timing.CurTime;
            var minutes = $"{expiresIn.TotalMinutes:0.00}";
            tooltip.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("custom-exam-part-expiration-tooltip", ("minutes", minutes))));
            return tooltip;
        };

        DistanceSpin.InitDefaultButtons();
        ExpirationSpin.InitDefaultButtons();
    }

    protected override void EnteredTree()
    {
        TitleLabel.Text = Title;
    }

    public void SetData(CustomExamineData data, bool force = false)
    {
        // Simply to prevent e.g. a state reset from overwriting the data since the server is going to send a new comp state
        if (!force && data.LastUpdate < _lastUpdated)
            return;

        _lastData = data;
        _lastUpdated = data.LastUpdate;

        Content.TextRope = new Rope.Leaf(data.Content ?? String.Empty);
        NsfwCheckbox.Pressed = data.RequiresConsent;
        DistanceSpin.Value = data.VisibilityRange;
        ExpirationSpin.Value = data.ExpireTime.Ticks == 0 || data.ExpireTime < _timing.CurTime
            ? 0
            : (int) Math.Round((data.ExpireTime - _timing.CurTime).TotalMinutes); // TODO rounding is bad
    }

    public CustomExamineData GetData() =>
        new()
        {
            Content = Rope.Collapse(Content.TextRope),
            RequiresConsent = NsfwCheckbox.Pressed,
            VisibilityRange = DistanceSpin.Value,
            // Adding a little to account for rounding above so the error doesn't keep adding up
            ExpireTime = _timing.CurTime + TimeSpan.FromMinutes(ExpirationSpin.Value + 0.4),
            LastUpdate = _lastUpdated
        };
}

