- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  requirements:
  - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
    min: 54000 # Floofstation - 15 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    min: 14400 # Floofstation - 4 hours
  - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - Shadowkin
        - !type:CharacterTraitRequirement
          traits:
            - ShadowkinBlackeye

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
