- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  requirements:
  - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
    min: 14400 # Floofstation - 4 hours
  - !type:CharacterTraitRequirement # Floofstation
    inverted: true
    traits:
      - Tiny # Floofstation - Too much of an advantage in a gunfight or stealth
