- type: entity
  name: blue pumpkin
  parent: FoodProduceBase
  id: FoodBluePumpkin
  description: A large, blue... berry. Seriously.
  components:
  - type: Item
    size: Small
  - type: FlavorProfile
    flavors:
      - bluepumpkin
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Ammonia
          Quantity: 10
        - ReagentId: Chlorine
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 10
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceBluePumpkin
        Quantity: 10
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/blue_pumpkin.rsi
  - type: Produce
    seedId: bluePumpkin
  - type: Damageable
    damageContainer: Biological
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 16
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: anomaly berry
  description: A strange blue fruit. Something about it doesn't seem right.
  parent: FoodProduceBase
  id: FoodAnomalyBerry
  components:
  - type: FlavorProfile
    flavors:
      - strange
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/anomaly_berry.rsi
    state: produce
  - type: Produce
    seedId: anomalyBerry
  - type: Food
    trash:
    - EffectAnomalyFloraBulb # Random loot
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 2
        - ReagentId: Artifexium
          Quantity: 1
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: humpshroom
  parent: FoodProduceBase
  id: FoodHumpShroom
  description: A sweet-smelling mushroom that excretes a sticky and arousing liquid.
  components:
  - type: FlavorProfile
    flavors:
      - mushroom
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: Philterex
          Quantity: 5
        - ReagentId: Cum
          Quantity: 20
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/humpshroom.rsi
  - type: Produce
    seedId: humpShroom
  - type: Extractable
    grindableSolutionName: food
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: breedshroom
  parent: FoodProduceBase
  id: FoodBreedShroom
  description: An overwhelmingly smelling mushroom that excretes an incredibly sticky and arousing liquid. It has been known to increase the population in colonies.
  components:
  - type: FlavorProfile
    flavors:
      - mushroom
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: Libidozenithizine
          Quantity: 2
        - ReagentId: Cum
          Quantity: 20
        - ReagentId: Philterex
          Quantity: 4
        - ReagentId: Happiness
          Quantity: 4
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/breedshroom.rsi
  - type: Produce
    seedId: breedShroom
  - type: Extractable
    grindableSolutionName: food
  - type: Tag
    tags:
    - Vegetable
