- type: entity
  name: meatwheat bushel
  description: Some blood-drenched wheat stalks. You can crush them into what passes for meat if you squint hard enough.
  id: MeatwheatBushel
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/meatwheat.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: UncookedAnimalProteins
          Quantity: 10
  - type: SpawnItemsOnUse
    items:
      - id: FoodMeatWheat
    sound:
      path: /Audio/Voice/Slime/slime_squish.ogg
  - type: Produce
    seedId: meatwheat

- type: entity
  name: papercane roll
  description: Why do we even need to grow paper?
  id: Papercane
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/papercane.rsi
  - type: SolutionContainerManager
  - type: Produce
    seedId: papercane
  - type: Log
    spawnedPrototype: SheetPaper1
    spawnCount: 2

- type: entity
  name: extradimensional orange
  parent: FoodProduceBase
  id: FoodExtradimensionalOrange
  description: You can hardly wrap your head around this thing.
  components:
  - type: FlavorProfile
    flavors:
      - truenature
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Haloperidol
          Quantity: 5
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/extradimensional_orange.rsi
    scale: 0.5,0.5
  - type: Produce
    seedId: extradimensionalOrange
  - type: PotencyVisuals
    minimumScale: 0.5 # reduce this in size because the sprite is way too big
    maximumScale: 1
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceOrange
        Quantity: 10
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: golden apple
  parent: FoodProduceBase
  id: FoodGoldenApple
  description: It should be shaped like a cube, shouldn't it?
  components:
  - type: FlavorProfile
    flavors:
      - apple
      - metallic
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
        - ReagentId: DoctorsDelight
          Quantity: 13
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/golden_apple.rsi
  - type: Produce
    seedId: goldenApple
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceApple
        Quantity: 10
      - ReagentId: Gold
        Quantity: 10
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: capfruit
  parent: FoodProduceBase
  id: FoodRealCapfruit
  description: A soft but smooth gun-shaped fruit.
  components:
  - type: FlavorProfile
    flavors:
      - plastic
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Sulfur
          Quantity: 5
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/capfruit.rsi
  - type: Produce
    seedId: realCapfruit
  - type: Food
    trash: RevolverCapGun
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: capfruit
  parent: FoodRealCapfruit
  id: FoodFakeCapfruit
  suffix: Fake
  components:
  - type: Produce
    seedId: fakeCapfruit
  - type: Food
    trash: RevolverCapGunFake

- type: entity
  name: holymelon
  parent: [FoodProduceBase, ItemHeftyBase]
  id: FoodHolymelon
  description: The water within this melon has been blessed by some deity that's particularly fond of watermelon.
  components:
  - type: Item
    size: Small
  - type: FlavorProfile
    flavors:
      - holy
      - watermelon
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 5
        - ReagentId: HolyWater
          Quantity: 10
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/holymelon.rsi
  - type: Produce
    seedId: watermelon
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Wine
        Quantity: 20
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: SliceableFood
    count: 5
    slice: FoodHolymelonSlice
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: holymelon slice
  parent: ProduceSliceBase
  id: FoodHolymelonSlice
  description: Juicy golden and red slice.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - holy
      - watermelon
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/holymelon.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 1
        - ReagentId: HolyWater
          Quantity: 2
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Wine
        Quantity: 4
  - type: Tag
    tags:
    - Fruit

- type: entity
  parent: FoodProduceBase
  id: FoodWorldPeas
  name: cluster of world peas
  description: It's rumored to bring peace to any who consume it.
  components:
  - type: FlavorProfile
    flavors:
      - numbingtranquility
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 8
        reagents:
        - ReagentId: Happiness
          Quantity: 3
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Pax
          Quantity: 2
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/world_pea.rsi
  - type: Produce
    seedId: worldPea
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: blue pumpkin
  parent: FoodProduceBase
  id: FoodBluePumpkin
  description: A large, blue... berry. Seriously.
  components:
  - type: Item
    size: Small
  - type: FlavorProfile
    flavors:
      - bluepumpkin
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Ammonia
          Quantity: 10
        - ReagentId: Chlorine
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 10
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceBluePumpkin
        Quantity: 10
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/blue_pumpkin.rsi
  - type: Produce
    seedId: bluePumpkin
  - type: Damageable
    damageContainer: Biological
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 16
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Tag
    tags:
    - Fruit

- type: entity
  parent: FoodProduceBase
  id: FoodCherry
  name: cherry
  description: Juicy red cherry with a pit inside.
  components:
  - type: FlavorProfile
    flavors:
    - cherry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 6
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 3
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceCherry
        Quantity: 5
  - type: Food
    trash: TrashCherryPit
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/cherry.rsi
  - type: Produce
    seedId: cherry
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: cherry pit
  parent: FoodInjectableBase
  id: TrashCherryPit
  components:
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/cherry.rsi
    state: pit
  - type: Item
    sprite: Floof/Objects/Specific/Hydroponics/cherry.rsi
    heldPrefix: pit
  - type: Tag
    tags:
    - Recyclable
    - Trash
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 1
        reagents:
        - ReagentId: Toxin
          Quantity: 1
  - type: Extractable
    grindableSolutionName: food
  - type: Seed
    seedId: cherry
  - type: SpaceGarbage
  - type: BadFood

- type: entity
  name: anomaly berry
  description: A strange blue fruit. Something about it doesn't seem right.
  parent: FoodProduceBase
  id: FoodAnomalyBerry
  components:
  - type: FlavorProfile
    flavors:
      - strange
  - type: Sprite
    sprite: Floof/Objects/Specific/Hydroponics/anomaly_berry.rsi
    state: produce
  - type: Produce
    seedId: anomalyBerry
  - type: Food
    trash: EffectAnomalyFloraBulb # Random loot
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 2
        - ReagentId: Artifexium
          Quantity: 1
  - type: Tag
    tags:
    - Fruit
